# Generated by Django 4.2.6 on 2023-10-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome do Pet")),
                (
                    "telefone",
                    models.IntegerField(max_length=11, verbose_name="Telefone"),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("segunda", "Segunda"),
                            ("terça", "Terça"),
                            ("quarta", "Quarta"),
                            ("quinta", "Quinta"),
                            ("sexta", "Sexta"),
                            ("sábado", "Sábado"),
                        ],
                        max_length=10,
                        verbose_name="Dia da Reserva",
                    ),
                ),
                ("observacoes", models.TextField()),
            ],
        ),
    ]
