# Generated by Django 4.2.6 on 2023-10-14 19:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_reserva_dia_alter_reserva_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
