# Generated by Django 4.2.6 on 2023-10-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_reserva_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
    ]
