# Generated by Django 4.2.6 on 2023-10-14 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_reserva_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="data_envio",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Banho marcado em",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reserva",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
